import {Lexend_Deca} from "next/font/google"
import "./globals.css";

const myFont = Lexend_Deca({
  subsets: ['latin'],
  variable: '--my-font'
})

export const metadata = {
  title: "My React Weather",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.variable} font-sans bg-indigo-400 antialiasing`}>{children}</body>
    </html>
  );
}
